import { describe, it, expect } from 'vitest';
import { parse } from '../utils/parsers/molParser';

describe('molParser', () => {
    it('should parse a valid MOL file', async () => {
        // Minimal MOL file for methane
        const molContent = `Methane
  Generated by test
  2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8900   -0.6293    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8900    0.6293    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8900   -0.6293    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8900    0.6293    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
M  END
`;
        const { atoms, lattice } = await parse(molContent);
        
        expect(atoms.length).toBe(5);
        expect(atoms[0].element).toBe('C');
        expect(atoms[0].x).toBe(-0.0000);
        expect(atoms[0].y).toBe(0.0000);
        expect(atoms[0].z).toBe(0.0000);
        expect(atoms[1].element).toBe('H');
        expect(atoms[1].x).toBe(-0.8900);
        expect(lattice).toBeNull();
    });

    it('should parse RDKit MOL file', async () => {
        // RDKit generated MOL file for acetic acid
        const molContent = `RDKit          2D

 12 14  0  0  0  0  0  0  0  0999 V2000
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0490   -2.0490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2990   -3.3481    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7990   -3.3481    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0490   -2.0490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  4  7  1  0
  7  8  2  0
  8  9  1  0
  9 10  2  0
 10 11  1  0
 11 12  2  0
  6  1  1  0
 12  7  1  0
 12  3  1  0
M  END
`;
        const { atoms, lattice } = await parse(molContent);
        
        expect(atoms.length).toBe(12);
        expect(atoms[0].element).toBe('C');
        expect(atoms[0].x).toBe(1.5000);
        expect(atoms[0].y).toBe(0.0000);
        expect(atoms[0].z).toBe(0.0000);
        expect(lattice).toBeNull();
    });

    it('should throw error if no atoms found', async () => {
        const invalidContent = `Invalid
  MOL
  File

  0  0  0  0  0  0  0  0  0  0999 V2000
`;
        await expect(parse(invalidContent)).rejects.toThrow('MOL parsing failed');
    });
});